# Generated by Django 5.1.2 on 2024-11-04 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0005_setting_description_alter_setting_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='version',
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('ERROR', 'Error')], max_length=50)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_core_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
