version: '3.8'

services:
  admin_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: admin_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    mem_limit: 512m

  admin_postgres:
    image: postgres:13
    container_name: admin_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin_django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - admin_postgres
      - admin_elasticsearch