version: '3.8'

services:
  admin_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: admin_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    mem_limit: 512m

  admin_postgres:
    image: postgres:13
    container_name: admin_postgres
    environment:
      POSTGRES_USER: adminpavel
      POSTGRES_PASSWORD: Pavel180400AdminOvhQEIHUSR6U9IP
      POSTGRES_DB: django_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminpavel"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin_django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://adminpavel:Pavel180400AdminOvhQEIHUSR6U9IP@admin_postgres:5432/django_db
      - ELASTICSEARCH_HOST=http://admin_elasticsearch:9200
      - DJANGO_SUPERUSER_USERNAME=adminpavel
      - DJANGO_SUPERUSER_PASSWORD=Pavel180400AdminOvhQEIHUSR6U9IP
      - DJANGO_SUPERUSER_EMAIL=admin@delhomme.ovh
    depends_on:
      - admin_postgres
      - admin_elasticsearch